name: Build & Deploy Master Branch

# Run this workflow every time a new commit pushed to the repository
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 7.3.0
      - name: Compile
        run: npm install
      - name: Set Version
        id: set-version
        run: |
          RAW_VERSION=$(echo $(grep version package.json))
          SNAPSHOT_VERSION=$(echo "${RAW_VERSION/"\""version"\"": "\""/}")
          VERSION=$(echo "${SNAPSHOT_VERSION/-SNAPSHOT"\"",/}")
          echo "Version ${VERSION} will be released!"
          echo ::set-output name=version::${VERSION}
  Docker:
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push with RevisionId tag
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: swiftqueuetest/swiftqueue-angular:${{needs.Build.outputs.version}},swiftqueuetest/swiftqueue-angular:latest
          context: ./
          file: ./Dockerfile
  Deploy:
    runs-on: ubuntu-latest
    needs: [Build, Docker]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Production
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade swiftqueue-angular ./helm/swiftqueue-angular --set-string image.tag=${{needs.Build.outputs.version}}
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
  UpdateVersion:
    runs-on: ubuntu-latest
    needs: [Build, Deploy]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Package Version
        run: |
          NEXT_VERSION=$(echo ${{needs.Build.outputs.version}} | awk -F. -v OFS=. '{$NF++;print}')-SNAPSHOT
          echo "Setting next snapshot version ${NEXT_VERSION}"
          sed -i 's/"version":"${{needs.Build.outputs.version}}"/"version":"${NEXT_VERSION}"/g' package.json
      - name: Commit files
        run: |
          git config --local user.email "github@users.noreply.github.com"
          git config --local user.name "Github CI/CD"
          git commit -m "Updated Package for the next version" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
