name: Build & Deploy Master Branch

# Run this workflow every time a new commit pushed to the repository
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - synchronize
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 7.3.0
      - name: Compile
        run: npm install --aot=false
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        #        if: github.ref == 'refs/heads/master'
        with:
          name: app-artifact
          path: ./Dockerfile
  Docker:
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: app-artifact
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push with RevisionId tag
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: swiftqueuetest/swiftqueue-angular:${{ github.sha }},swiftqueuetest/swiftqueue-angular:latest
          context: ./
          file: ./Dockerfile
  Deploy:
    runs-on: ubuntu-latest
    needs: Docker
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to Production
        uses: steebchen/kubectl@master
        env:
          # A base-64 representation of ~/.kube/config file
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image deployment/swiftqueue-angular swiftqueue-angular=swiftqueuetest/swiftqueue-angular:${{ github.sha }} -n swiftqueue
