name: 'Nightly Artifacts Cleanup'
on:
  schedule:
    - cron: '0 0 * * *' # every night at 0 UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0 # Setting this to 0 will delete all artifacts
